FORMAT: 1A

# TAS API
###**TAS REST SPECIFICATION API: TAS (Telrock Account Servicing, formally known as TSYS Account Servicing)**

# Group ID&V PROCESS
**The resources**: 
- **GET idv/process(Start a new ID&V process)**
- **POST idv/process(Submit a collection of ID&V answers)**


## ID&V PROCESS [/idv/process]
### ID&V PROCESS - RETRIEVE QUESTIONS[POST] 
- **METHOD:** POST /idv/process 
- **REQUEST OBJECT:** (empty body) or hash-code 
- **RESPONSE Object:** IdvQuestionVO 
- **DESCRIPTION:** This initial call will start a new ID&V process. The request can either be empty, or contain the 1-time hashcode.

+ Response 200 (application/json)

        {
            "info": {
            "text": "Some information to display in a pop-up",
            "key": "some.info.text"
        },
        "errors": [
        {
            "id": 12345,
            "field": "currency",
            "text": "You must include a currency",
            "key": "error.missing.currency"
        },
        {
            "id": 12345,
            "field": "amount",
            "text": "Amount must be smaller than 10.00",
            "key": "error.maximum.amount"
        }
        ],
        "data": [
        {  
          "id":12345,
          "label":"customer.login.customer.name",
          "field":"customerVO.lastName",
          "channel":"WEB",
          "whenLogged":1416487579246
        },
        {  
          "id":12346,
          "label":"customer.login.primary.phone.number",
          "field":"customerVO.phone",
          "channel":"WEB",
          "whenLogged":1416487579246
        },
        {  
          "id":12347,
          "label":"customer.login.dob",
          "field":"customerVO.dateOfBirth",
          "channel":"WEB",
          "whenLogged":1416487579246
        },
        {  
          "id":12348,
          "label":"customer.login.post.code",
          "field":"customerVO.postalCode",
          "channel":"WEB",
          "whenLogged":1416487579246
        }
        ]
        }
           

### ID&V PROCESS - SAVE ANSWERS[PUT]
- **METHOD:** PUT /idv/process 
- **REQUEST OBJECT:** IDVAnswerVO
- **RESPONSE Object:** IdvQuestionVO 
- **DESCRIPTION:** This method will evaluate the submitted answers and  return; a group of questions to ask.

- An **ANSWER** to each ID&V question would be sent to the backend in array of objects like this:
**{
    "answer": "12/11/1981",
    "idvQuestionId": 12345
}**

+ Response 200 (application/json)
    
            {
            "info": {
            "text": "Some information to display in a pop-up",
            "key": "some.info.text"
        },
        "errors": [
        {
            "id": 12345,
            "field": "currency",
            "text": "You must include a currency",
            "key": "error.missing.currency"
        },
        {
            "id": 12345,
            "field": "amount",
            "text": "Amount must be smaller than 10.00",
            "key": "error.maximum.amount"
        }
        ],
        "data": [
        {  
          "id":12345,
          "label":"customer.login.customer.name",
          "field":"customerVO.lastName",
          "channel":"WEB",
          "whenLogged":1416487579246
        },
        {  
          "id":12346,
          "label":"customer.login.primary.phone.number",
          "field":"customerVO.phone",
          "channel":"WEB",
          "whenLogged":1416487579246
        },
        {  
          "id":12347,
          "label":"customer.login.dob",
          "field":"customerVO.dateOfBirth",
          "channel":"WEB",
          "whenLogged":1416487579246
        },
        {  
          "id":12348,
          "label":"customer.login.post.code",
          "field":"customerVO.postalCode",
          "channel":"WEB",
          "whenLogged":1416487579246
        }
        ]
        }


# Group CAMPAIGN API
**The resources**: 
- **GET campaign  --> (List all campaigns)**
- **GET campaign/{id}  --> (Lookup the requested campaign)**
- **POST campaign  --> (Add a new campaign)**
- **PUT campaign/{id}  --> (Update an existing campaign)**
- **DELETE campaign/{id}  --> (Delete a campaign)**
- **GET campaign/schedule  --> (List all campaigns schedules)**
- **GET campaign/{id}/schedule  --> (List all schedules for a specific campaign)**
- **GET campaign/schedule/{id}  --> (Lookup the selected schedule)**
- **POST campaign/{id}/schedule  --> (Add new schedule(s) to campaign)**
- **PUT campaign/schedule/{id}  --> (Update an existing schedule)**
- **DELETE campaign/schedule/{id}  --> (Delete a schedule)**
- **GET campaign/schedule/account  --> (List all account campaign schedules)**
- **GET campaign/{id}/schedule/account  --> (List all account schedules for a selected campaign)**
- **GET campaign/schedule/{id}/account  --> (List all accounts for a selected schedule)**
- **GET campaign/{id}/account  --> (Lookup a selected account schedule)**
- **POST campaign/schedule/{id}/account  --> (Add new account(s) to a campaign schedule)**
- **PUT campaign/schedule/account/{id}  --> (Update an existing account schedule)**
- **DELETE campaign/schedule/account/{id}  --> (Delete an account schedule)**

- **CampaignVO:** A campaign object represents a pre-defined schedule of customer contacts

## CAMPAIGN API [/campaign]
### CAMPAIGN - RETRIEVE CAMPAIGNS[GET]
- **METHOD:** GET /campaign
- **REQUEST OBJECT:** (empty body)
- **RESPONSE Object:** IdvQuestionVO 
- **DESCRIPTION:** List all campaigns



+ Response 200 (application/json)

            {
            {
            "info": {
            "text": "Some information to display in a pop-up",
            "key": "some.info.text"
            }
            "errors": [
                {
                    "id": 12345,
                    "field": "currency",
                    "text": "You must include a currency",
                    "key": "error.missing.currency"
                },
                {
                    "id": 12346,
                    "field": "amount",
                    "text": "Amount must be smaller than 10.00",
                    "key": "error.maximum.amount"
                }
                ],
                "data": [
                {
                    "id": 12347,
                    "paymentSourceVO": null,
                    "amount": 20,
                    "currency": null,
                    "whenLogged": 1420794940392,
                    "whenComplete": null,
                    "status": null,
                    "attributes": { },
                    "customerAccountId": 0,
                    "paymentScheduleId": 0
                },
                {
                    "id": 54321,
                    "paymentSourceVO": null,
                    "amount": 2,
                    "currency": "GBP",
                    "whenLogged": 1420794940393,
                    "whenComplete": null,
                    "status": null,
                    "attributes": { },
                    "customerAccountId": 0,
                    "paymentScheduleId": 0
                }
                ]
            }


## CAMPAIGN API [/campaign/{id}]
### CAMPAIGN - Lookup the requested campaign[GET]
- **METHOD:** GET /campaign/{id}
- **REQUEST OBJECT:** {id: campaignID}
- **RESPONSE Object:** IdvQuestionVO 
- **DESCRIPTION:** It will provide the specific campaign


+ Response 200 (application/json)

            {
            {
            "info": {
            "text": "Some information to display in a pop-up",
            "key": "some.info.text"
            }
            "errors": [
                {
                    "id": 12345,
                    "field": "currency",
                    "text": "You must include a currency",
                    "key": "error.missing.currency"
                },
                {
                    "id": 12346,
                    "field": "amount",
                    "text": "Amount must be smaller than 10.00",
                    "key": "error.maximum.amount"
                }
                ],
                "data": [
                {
                    "id": 12347,
                    "paymentSourceVO": null,
                    "amount": 20,
                    "currency": null,
                    "whenLogged": 1420794940392,
                    "whenComplete": null,
                    "status": null,
                    "attributes": { },
                    "customerAccountId": 0,
                    "paymentScheduleId": 0
                },
                {
                    "id": 54321,
                    "paymentSourceVO": null,
                    "amount": 2,
                    "currency": "GBP",
                    "whenLogged": 1420794940393,
                    "whenComplete": null,
                    "status": null,
                    "attributes": { },
                    "customerAccountId": 0,
                    "paymentScheduleId": 0
                }
                ]
            }


### CAMPAIGN - Add a new campaign[POST]
- **METHOD:** POST /campaign
- **REQUEST OBJECT:** (empty body)
- **RESPONSE Object:** IdvQuestionVO 
- **DESCRIPTION:** Add a new campaign


+ Response 200 (application/json)

            {
            {
            "info": {
            "text": "Some information to display in a pop-up",
            "key": "some.info.text"
            }
            "errors": [
                {
                    "id": 12345,
                    "field": "currency",
                    "text": "You must include a currency",
                    "key": "error.missing.currency"
                },
                {
                    "id": 12346,
                    "field": "amount",
                    "text": "Amount must be smaller than 10.00",
                    "key": "error.maximum.amount"
                }
                ],
                "data": [
                {
                    "id": 12347,
                    "paymentSourceVO": null,
                    "amount": 20,
                    "currency": null,
                    "whenLogged": 1420794940392,
                    "whenComplete": null,
                    "status": null,
                    "attributes": { },
                    "customerAccountId": 0,
                    "paymentScheduleId": 0
                },
                {
                    "id": 54321,
                    "paymentSourceVO": null,
                    "amount": 2,
                    "currency": "GBP",
                    "whenLogged": 1420794940393,
                    "whenComplete": null,
                    "status": null,
                    "attributes": { },
                    "customerAccountId": 0,
                    "paymentScheduleId": 0
                }
                ]
            }

## CAMPAIGN API [/campaign/{id}]
### CAMPAIGN - Update an existing campaign[PUT]
- **METHOD:** PUT /campaign/
- **REQUEST OBJECT:** (empty body)
- **RESPONSE Object:** IdvQuestionVO 
- **DESCRIPTION:** Update an existing campaign


+ Response 200 (application/json)

            {
            {
            "info": {
            "text": "Some information to display in a pop-up",
            "key": "some.info.text"
            }
            "errors": [
                {
                    "id": 12345,
                    "field": "currency",
                    "text": "You must include a currency",
                    "key": "error.missing.currency"
                },
                {
                    "id": 12346,
                    "field": "amount",
                    "text": "Amount must be smaller than 10.00",
                    "key": "error.maximum.amount"
                }
                ],
                "data": [
                {
                    "id": 12347,
                    "paymentSourceVO": null,
                    "amount": 20,
                    "currency": null,
                    "whenLogged": 1420794940392,
                    "whenComplete": null,
                    "status": null,
                    "attributes": { },
                    "customerAccountId": 0,
                    "paymentScheduleId": 0
                },
                {
                    "id": 54321,
                    "paymentSourceVO": null,
                    "amount": 2,
                    "currency": "GBP",
                    "whenLogged": 1420794940393,
                    "whenComplete": null,
                    "status": null,
                    "attributes": { },
                    "customerAccountId": 0,
                    "paymentScheduleId": 0
                }
                ]
            }


## /campaign/{id} [/campaign/{id}]
### CAMPAIGN - Delete a campaign[DELETE]
- **METHOD:** DELETE /campaign/{ID}
- **REQUEST OBJECT:** (empty body)
- **RESPONSE Object:** IdvQuestionVO 
- **DESCRIPTION:** Delete a campaign


+ Response 200 (application/json)

 {
            {
            "info": {
            "text": "Some information to display in a pop-up",
            "key": "some.info.text"
            }
            "errors": [
                {
                    "id": 12345,
                    "field": "currency",
                    "text": "You must include a currency",
                    "key": "error.missing.currency"
                },
                {
                    "id": 12346,
                    "field": "amount",
                    "text": "Amount must be smaller than 10.00",
                    "key": "error.maximum.amount"
                }
                ],
                "data": [
                {
                    "id": 12347,
                    "paymentSourceVO": null,
                    "amount": 20,
                    "currency": null,
                    "whenLogged": 1420794940392,
                    "whenComplete": null,
                    "status": null,
                    "attributes": { },
                    "customerAccountId": 0,
                    "paymentScheduleId": 0
                },
                {
                    "id": 54321,
                    "paymentSourceVO": null,
                    "amount": 2,
                    "currency": "GBP",
                    "whenLogged": 1420794940393,
                    "whenComplete": null,
                    "status": null,
                    "attributes": { },
                    "customerAccountId": 0,
                    "paymentScheduleId": 0
                }
                ]
            }


## CAMPAIGN API [/campaign/schedule]
### CAMPAIGN - List all campaigns schedules[GET]
- **METHOD:** GET /campaign/schedule
- **REQUEST OBJECT:** (empty body)
- **RESPONSE Object:** IdvQuestionVO 
- **DESCRIPTION:** List all campaigns schedules


+ Response 200 (application/json)

 {
            {
            "info": {
            "text": "Some information to display in a pop-up",
            "key": "some.info.text"
            }
            "errors": [
                {
                    "id": 12345,
                    "field": "currency",
                    "text": "You must include a currency",
                    "key": "error.missing.currency"
                },
                {
                    "id": 12346,
                    "field": "amount",
                    "text": "Amount must be smaller than 10.00",
                    "key": "error.maximum.amount"
                }
                ],
                "data": [
                {
                    "id": 12345,
                    "day": 1,
                    "time": "12:00",
                    "whenLogged": 1416477449177,
                    "campaignVO": {
                        "id": 12345,
                        "name": "High-risk Treatment",
                        "refComponentVO": {
                            "id": 12345,
                            "component": "ACCOUNT_ALERT"
                        },
                        "type": "COLLECTIONS",
                        "whenLogged": 1416477449177,
                        "segments": [
                        "high risk"
                        ]
                    },
                    "messageTemplateId": 12345
                }
                ]
            }

## CAMPAIGN API [/campaign/{id}/schedule]
### CAMPAIGN - List all schedules for a specific campaign[GET]
- **METHOD:** GET /campaign/{id}/schedule
- **REQUEST OBJECT:** (empty body)
- **RESPONSE Object:** IdvQuestionVO 
- **DESCRIPTION:** List all schedules for a specific campaign


+ Response 200 (application/json)


## CAMPAIGN API [/campaign/schedule/{id}]
### CAMPAIGN - Lookup the selected schedule[GET]
- **METHOD:** GET /campaign/schedule/{id}
- **REQUEST OBJECT:** (empty body)
- **RESPONSE Object:** IdvQuestionVO 
- **DESCRIPTION:** Lookup the selected schedule

+ Response 200 (application/json)




## CAMPAIGN API [/campaign/{id}/schedule]
### CAMPAIGN - Add new schedule(s) to campaign[POST]
- **METHOD:** POST /campaign/{id}/schedule
- **REQUEST OBJECT:** (empty body)
- **RESPONSE Object:** IdvQuestionVO 
- **DESCRIPTION:** Add new schedule(s) to campaign


+ Response 200 (application/json)




## CAMPAIGN API [/campaign/schedule/{id}]
### CAMPAIGN - Update an existing schedule[PUT]
- **METHOD:** PUT /campaign/schedule/{id}
- **REQUEST OBJECT:** {id: campaignID}
- **RESPONSE Object:** IdvQuestionVO 
- **DESCRIPTION:** Update an existing schedule


+ Response 200 (application/json)



## CAMPAIGN API [/campaign/schedule/{id}]
### CAMPAIGN - Delete a schedule[DELETE]
- **METHOD:** DELETE /campaign/schedule/{id}
- **REQUEST OBJECT:** (empty body)
- **RESPONSE Object:** IdvQuestionVO 
- **DESCRIPTION:** Delete a schedule


+ Response 200 (application/json)



## CAMPAIGN API [/campaign/schedule/account]
### CAMPAIGN - List all account campaign schedules[GET]
- **METHOD:** GET /campaign/schedule/account
- **REQUEST OBJECT:** (empty body)
- **RESPONSE Object:** IdvQuestionVO 
- **DESCRIPTION:** List all account campaign schedules


+ Response 200 (application/json)


## CAMPAIGN API [/campaign/{id}/schedule/account]
### CAMPAIGN - List all account schedules for a selected campaign[GET]
- **METHOD:** GET /campaign/{id}/schedule/account
- **REQUEST OBJECT:** (empty body)
- **RESPONSE Object:** IdvQuestionVO 
- **DESCRIPTION:** List all account schedules for a selected campaign


+ Response 200 (application/json)

## CAMPAIGN API [/campaign/schedule]
### CAMPAIGN - List all campaigns schedules[GET]
- **METHOD:** GET /campaign/schedule
- **REQUEST OBJECT:** (empty body)
- **RESPONSE Object:** IdvQuestionVO 
- **DESCRIPTION:** List all campaigns schedules


+ Response 200 (application/json)


## CAMPAIGN API [/campaign/schedule/{id}/account]
### CAMPAIGN - List all accounts for a selected schedule[GET]
- **METHOD:** GET /campaign/schedule/{id}/account
- **REQUEST OBJECT:** (empty body)
- **RESPONSE Object:** IdvQuestionVO 
- **DESCRIPTION:** List all accounts for a selected schedule


+ Response 200 (application/json)


## CAMPAIGN API [/campaign/{id}/account]
### CAMPAIGN - Lookup a selected account schedule[GET]
- **METHOD:** GET /campaign/{id}/account
- **REQUEST OBJECT:** (empty body)
- **RESPONSE Object:** IdvQuestionVO 
- **DESCRIPTION:** Lookup a selected account schedule

+ Response 200 (application/json)


## CAMPAIGN API [/campaign/schedule/{id}/account]
### CAMPAIGN - Add new account(s) to a campaign schedule[POST]
- **METHOD:** POST /campaign/schedule/{id}/account
- **REQUEST OBJECT:** (empty body)
- **RESPONSE Object:** IdvQuestionVO 
- **DESCRIPTION:** Add new account(s) to a campaign schedule


+ Response 200 (application/json)

## CAMPAIGN API [/campaign/schedule/account/{id}]
### CAMPAIGN - Update an existing account schedule[PUT]
- **METHOD:** PUT /campaign/schedule/account/{id}
- **REQUEST OBJECT:** (empty body)
- **RESPONSE Object:** IdvQuestionVO 
- **DESCRIPTION:** Update an existing account schedule


+ Response 200 (application/json)

## CAMPAIGN API [/campaign/schedule/account/{id}]
### CAMPAIGN - Delete an account schedule[DELETE]
- **METHOD:** DELETE /campaign/schedule/account/{id}
- **REQUEST OBJECT:** (empty body)
- **RESPONSE Object:** IdvQuestionVO 
- **DESCRIPTION:** Delete an account schedule

+ Response 200 (application/json)


## Login [/payment/account/<id>/plan]
### Login [POST]
+ Body
    + name = "myName" (required, String, "myName")
    + password = "myPassword" (required, String, "myPassword")

+ Request (application/json)  
    
            {
                "id": 12345,
                "period": "MONTHLY",
                "total": 100.00,
                "status": "NEW",
                "whenLogged": 1416830342676,
                "attributes": {
                    "initialPaymentAmount": "4",
                    "installmentAmount": "1"
                }
            }

+ Response 201 (application/json)

## Login [/authentication]
### Login [POST]
+ Body
    + name = "myName" (required, String, "myName")
    + password = "myPassword" (required, String, "myPassword")

+ Request (application/json)  
    
            {
            "name":"myName"
            "password":"myPassword"
            }

+ Response 201 (application/json)

## getAllAuthenticationUserVO1 [/authentication/user]
### getAllAuthenticationUserVO [GET] 

+ Body
    + name = "name" (optional, String, "myName")
    + groupId = "groupId" (optional, long, "1")

+ Response 200 (application/json)

        [
            {
            "id": 12345,
            "name": "mr user",
            "email": "test@test.com",
            "password": null,
            "requirePasswordChange": false,
            "failedAuthentications": 0,
            "lastLoginTime": 1416578523863,
            "passwordLastUpdated": 1416578523863,
            "superUser": false,
            "whenLogged": 1416578523863},
            {
            "id": 11111,
            "name": "mr user",
            "email": "test@test.com",
            "password": null,
            "requirePasswordChange": false,
            "failedAuthentications": 0,
            "lastLoginTime": 1416578523863,
            "passwordLastUpdated": 1416578523863,
            "superUser": false,
            "whenLogged": 1416578523863},
            {
            "id": 1222222,
            "name": "mr user",
            "email": "test@test.com",
            "password": null,
            "requirePasswordChange": false,
            "failedAuthentications": 0,
            "lastLoginTime": 1416578523863,
            "passwordLastUpdated": 1416578523863,
            "superUser": false,
            "whenLogged": 1416578523863
            }
        ]
        
## getAllAuthenticationUserVO [/authentication/user/{name}/{groupId}]
### getAllAuthenticationUserVO [GET]

+ Body
    + name = "name" (optional, String, "myName")
    + groupId = "groupId" (optional, long, "1")

+ Response 200 (application/json)

        [
            {
            "id": 12345,
            "name": "mr user",
            "email": "test@test.com",
            "password": null,
            "requirePasswordChange": false,
            "failedAuthentications": 0,
            "lastLoginTime": 1416578523863,
            "passwordLastUpdated": 1416578523863,
            "superUser": false,
            "whenLogged": 1416578523863},
            {
            "id": 11111,
            "name": "mr user",
            "email": "test@test.com",
            "password": null,
            "requirePasswordChange": false,
            "failedAuthentications": 0,
            "lastLoginTime": 1416578523863,
            "passwordLastUpdated": 1416578523863,
            "superUser": false,
            "whenLogged": 1416578523863},
            {
            "id": 1222222,
            "name": "mr user",
            "email": "test@test.com",
            "password": null,
            "requirePasswordChange": false,
            "failedAuthentications": 0,
            "lastLoginTime": 1416578523863,
            "passwordLastUpdated": 1416578523863,
            "superUser": false,
            "whenLogged": 1416578523863
            }
        ]

## getCustomerByID [/customer/{id}]
### getCustomerByID [GET]

+ Body
    + name = "name" (optional, String, "myName")
    + groupId = "groupId" (optional, long, "1")

+ Response 200 (application/json)

        {
            "info": {
            },  
            "errors": [
            ], 
            "data": [
                {
                    "id": 12345,
                    "title": "Mr",
                    "firstName": "Peter",
                    "lastName": "Parker",
                    "hostReference": null,
                    "status": "ACTIVE",
                    "attributes": {
                        "uniqueCustomerId": "123456",
                        "maritalStatus": 10,
                        "timeZone":"Single"
                    },
                    "dateOfBirth": 1416484679669,
                    "whenLogged": 1416484679669
                }
            ]
        }

## getCustomerAddressByCustomerID [/customer/{id}/contact]
### getCustomerAddressByCustomerID [GET]

+ Body
    + name = "name" (optional, String, "myName")
    + groupId = "groupId" (optional, long, "1")

+ Response 200 (application/json)

        {
            "info": {
            },  
            "errors": [
            ], 
            "data": [
                {
                    "id": 12345, 
                    "name": "My Mobile", 
                    "active": true, 
                    "address": "447777777777", 
                    "primary": true, 
                    "type": "MOBILE", 
                    "whenLogged": 1422968205528
                },
                {
                    "id": 12345, 
                    "active": true, 
                    "address": "jose@telrock.com", 
                    "name": "My Email", 
                    "primary": true, 
                    "type": "EMAIL", 
                    "whenLogged": 1422968205528
                }
            ]
        }
                  
## getCustomerAccountByID [/customer/account/{id}]
### getCustomerAccountByID [GET]

+ Body
    + name = "name" (optional, String, "myName")
    + groupId = "groupId" (optional, long, "1")

+ Response 200 (application/json)

        {
            "info": {
            }, 
            "errors": [
            ], 
            "data": [
                {
                "id": 1, 
                "refAccountTypeVO": {
                    "id": 12345, 
                    "type": "Loan", 
                    "thirdPartyCode": "FGW", 
                    "description": null
                }, 
                "brandVO": {
                    "id": 12345, 
                    "byDefault": false, 
                    "name": "Bank"
                }, 
                "accountNumber": "1234567890", 
                "hostReference": null, 
                "status": "ACTIVE", 
                "whenLogged": 1422967780351, 
                "attributes" : {
                    "debtRef" : "003222003503",
                    "externalStatus" : "pre-write-off",
                    "clientStatus" : "E01",
                    "productType" : "LOAN",
                    "origProduct" : "CARD",
                    "productDescription" : "PLP LOAN",
                    "locationCode" : "102010",
                    "balancePrinciple" : "100",
                    "balanceInterest" : "1",
                    "balanceFees" : "1",
                    "balanceTotal" : "1",
                    "totalAmountDue" : "1000000",
                    "overLimitAmount" : "100",
                    "creditLimit" : "100",
                    "lastDebitAmount" : "100",
                    "lastPaymentAmount" : "10",
                    "minDue" : "10",
                    "daysInExcess" : "50",
                    "nextPayDate" : "1416484679669",
                    "lastDebitDate" : "1416484679669", 
                    "daysBeforeDueAlert" : "2",
                    "brandedProductLabel" : "PLP",
                    "dateLastPromiseBroken" : "1416484679669",
                    "paymentPlanTerm" : "12",
                    "paymentPlanDefarral" : "12",
                    "paymentPlanMinPayment" : "1", 
                    "brokenPromise" : true,
                    "randomToken" : "123213123213",
                    "delinquencyReason" : "NO",
                    "segmentationCode" : "asd"
                    }
                }
            ]
        }
   

## getPaymentPlanByAccountID [/payment/account/{id}/plan]
### getPaymentPlanByAccountID [GET]

+ Body
    + name = "name" (optional, String, "myName")
    + groupId = "groupId" (optional, long, "1")

+ Response 200 (application/json)

        {
            "info": {
            }, 
            "errors": [
            ], 
            "data": [
                {
                    "id": 1, 
                    "period": "MONTHLY", 
                    "total": 100, 
                    "status": "PROCESSING", 
                    "whenLogged": 1422964212850, 
                    "attributes": {
                        "auth-type": "SMS",
                        "type": "PAYNOW"
                    }
                },
                {
                    "id": 2, 
                    "period": "WEEKLY", 
                    "total": 1000000, 
                    "status": "PROCESSING", 
                    "whenLogged": 1420416000, 
                    "attributes": {
                        "auth-type": "SMS",
                        "type": "PLAN"
                    }
                },
                {
                    "id": 3, 
                    "period": "MONTHLY", 
                    "total": 500, 
                    "status": "NEW", 
                    "whenLogged": 1436054400, 
                    "attributes": {
                        "auth-type": "AUTOMATIC",
                        "type": "FDP"
                    }
                }
            ]
        }

## updatePaymentPlanByAccountID [/payment/account/plan/{id}]
### updatePaymentPlanByAccountID [PUT]

+ Body
    + name = "name" (optional, String, "myName")
    + groupId = "groupId" (optional, long, "1")

+ Response 200 (application/json)

        {
            "info": {
            }, 
            "errors": [
            ], 
            "data": [
                {
                    "id": 9, 
                    "period": "MONTHLY", 
                    "total": 100, 
                    "status": "PROCESSING", 
                    "whenLogged": 1422964212850, 
                    "attributes": {
                        "auth-type": "AUTOMATIC"
                    }
                }
            ]
        }

<!--## getPaymentPlanByAccountID [/payment/account/{id}/plan]-->
<!--### getPaymentPlanByAccountID [GET]-->

<!--+ Body-->
<!--    + name = "name" (optional, String, "myName")-->
<!--    + groupId = "groupId" (optional, long, "1")-->

<!--+ Response 200 (application/json)-->

<!--        {-->
<!--            "info": {-->
<!--            }, -->
<!--            "errors": [-->
<!--            ], -->
<!--            "data": [-->
<!--                {-->
<!--                    "id": 1, -->
<!--                    "period": "MONTHLY", -->
<!--                    "total": 100, -->
<!--                    "status": "PROCESSING", -->
<!--                    "whenLogged": 1422964212850, -->
<!--                    "attributes": {-->
<!--                        "auth-type": "SMS"-->
<!--                    }-->
<!--                },-->
<!--                {-->
<!--                    "id": 2, -->
<!--                    "period": "WEEKLY", -->
<!--                    "total": 1000000, -->
<!--                    "status": "PROCESSING", -->
<!--                    "whenLogged": 1420416000, -->
<!--                    "attributes": {-->
<!--                        "auth-type": "SMS"-->
<!--                    }-->
<!--                },-->
<!--                {-->
<!--                    "id": 3, -->
<!--                    "period": "MONTHLY", -->
<!--                    "total": 500, -->
<!--                    "status": "NEW", -->
<!--                    "whenLogged": 1436054400, -->
<!--                    "attributes": {-->
<!--                        "auth-type": "AUTOMATIC"-->
<!--                    }-->
<!--                }-->
<!--            ]-->
<!--        }-->
## getPaymentSourceVO [/wallet/paymentsource]
### getPaymentSourceVO [GET]

+ Body
    + name = "name" (optional, String, "myName")
    + groupId = "groupId" (optional, long, "1")

+ Response 200 (application/json)

        {
            "info": {
            },  
            "errors": [
            ], 
            "data": [
                {
                    "id": 12345, 
                    "name": "Lloyds card", 
                    "sequence": 1, 
                    "type": "VISA DEBIT", 
                    "active": true, 
                    "attributes": {
                        "nameOnCard": "Mr Alex Kidd", 
                        "expiry": "0116",
                        "alias" : "Mr Alex Kidd"
                    }, 
                    "whenLogged": 1421931849986, 
                    "accountNumber": "4444444444444"
                },
                {
                    "id": 12345, 
                    "name": "Lloyds card", 
                    "sequence": 0, 
                    "type": "VISA DEBIT", 
                    "active": true, 
                    "attributes": {
                        "nameOnCard": "Mr Smith", 
                        "expiry": "0116",
                        "alias" : "Mr Smith"
                    }, 
                    "whenLogged": 1421931849986, 
                    "accountNumber": "4444444444444"
                }
            ]
        }
        
## Notes Collection [/user/]
### List all Notes [GET]
+ Response 200 (application/json)

        [
        {"id": 35436,
         "user": "admin",
         "password": "admin",
         "name":"Johnny Agent"},
         {"id": 2,
         "user": "agent",
         "password": "agent",
         "name":"Johnny Agent"}]

## Notes Collection [/authentication/user/{user}]
### Create a Note [POST]
+ Request (application/json)

        {"id": 12345,
        "name": "mr_user",
        "password": "blablabla",
        "attributes": { 
            "att1": "att1_value",
            "att2": "att2_value" 
            }
        }
        
        

+ Response 201 (application/json)

        {"id": 3,
        "name": "mr_user3",
        "password": "blablabla3",
        "attributes":{
                "att1": "att1_value3",
                "att2": "att2_value3"
            }
        } 
        
<!--## getAllPaymentPlansForAccount [/payment/account/{id}/plan]-->
<!--### getAllPaymentPlansForAccount [GET]-->

<!--+ Body-->
<!--    + name = "name" (optional, String, "myName")-->
<!--    + groupId = "groupId" (optional, long, "1")-->

<!--+ Response 200 (application/json)-->

<!--        {-->
<!--            "info": {-->
<!--             }, -->
<!--            "errors": [-->
<!--            ], -->
<!--            "data": [-->
<!--                {-->
<!--                "id": 1, -->
<!--                "refAccountTypeVO": {-->
<!--                    "id": 12345, -->
<!--                    "type": "Loan", -->
<!--                    "thirdPartyCode": "FGW", -->
<!--                    "description": null-->
<!--                }, -->
<!--                "brandVO": {-->
<!--                    "id": 12345, -->
<!--                    "byDefault": false, -->
<!--                    "name": "Bank", -->
<!--                    "brandAlias": [ ]-->
<!--                }, -->
<!--                "accountNumber": "1234567890", -->
<!--                "hostReference": null, -->
<!--                "status": "ACTIVE", -->
<!--                "attributes": { "colour": "red", "count": 10 }, -->
<!--                "whenLogged": 1422967780351, -->
<!--                "customerVOList": [ {"id": 1} ]-->
<!--                }-->
<!--            ]-->
<!--        }-->
        
        
## getAllPaymentSchedule1 [/payment/account/plan/1/schedule]
### getAllPaymentSchedule1 [GET]

+ Body
    + name = "name" (optional, String, "myName")
    + groupId = "groupId" (optional, long, "1")

+ Response 200 (application/json)

        {
            "info": {
             }, 
            "errors": [
            ], 
            "data": [
                {
                    "id": 1, 
                    "paymentPlanVO": {
                            "id": 1, 
                            "period": "MONTHLY", 
                            "total": 100, 
                            "status": "NEW", 
                            "whenLogged": 1422964212850, 
                            "attributes": {
                                "auth-type": "SMS"
                                }
                            
                        }, 
                    "paymentVOList": [ { "id": 12345 } ], 
                    "amount": 10, 
                    "dueDate": 1422964439482, 
                    "status": "COMPLETE"
                }, 
               {
                    "id": 2, 
                    "paymentPlanVO": {
                            "id": 1, 
                            "period": "MONTHLY", 
                            "total": 100, 
                            "status": "NEW", 
                            "whenLogged": 1422964212850, 
                            "attributes": {
                                "auth-type": "SMS"
                                }
                            
                        }, 
                    "paymentVOList": [ { "id": 12345 } ], 
                    "amount": 15, 
                    "dueDate": 1422964439482, 
                    "status": "PROCESSING"
                },
                {
                    "id": 3, 
                    "paymentPlanVO": {
                            "id": 1, 
                            "period": "MONTHLY", 
                            "total": 100, 
                            "status": "NEW", 
                            "whenLogged": 1422964212850, 
                            "attributes": {
                                "auth-type": "SMS"
                                }
                            
                        }, 
                    "paymentVOList": [ { "id": 12345 } ], 
                    "amount": 20, 
                    "dueDate": 1422964439482, 
                    "status": "NEW"
                }

            ]
        }
        
## getAllPaymentSchedule2 [/payment/account/plan/2/schedule]
### getAllPaymentSchedule2 [GET]

+ Body
    + name = "name" (optional, String, "myName")
    + groupId = "groupId" (optional, long, "1")

+ Response 200 (application/json)

        {
            "info": {
             }, 
            "errors": [
            ], 
            "data": [
                {
                    "id": 1, 
                    "paymentPlanVO": {
                            "id": 2, 
                            "period": "WEEKLY", 
                            "total": 1000000, 
                            "status": "PROCESSING", 
                            "whenLogged": 1420416000, 
                            "attributes": {
                                "auth-type": "SMS"
                            }
                        }, 
                    "paymentVOList": [ { "id": 12345 } ], 
                    "amount": 200000, 
                    "dueDate": 1420416000, 
                    "status": "COMPLETE"
                }, 
               {
                    "id": 2, 
                    "paymentPlanVO": {
                            "id": 2, 
                            "period": "WEEKLY", 
                            "total": 1000000, 
                            "status": "PROCESSING", 
                            "whenLogged": 1420416000, 
                            "attributes": {
                                "auth-type": "SMS"
                            }
                        }, 
                    "paymentVOList": [ { "id": 12345 } ], 
                    "amount": 200000, 
                    "dueDate": 1423094400, 
                    "status": "PROCESSING"
                },
                {
                    "id": 3, 
                    "paymentPlanVO": {
                            "id": 2, 
                            "period": "WEEKLY", 
                            "total": 1000000, 
                            "status": "PROCESSING", 
                            "whenLogged": 1420416000, 
                            "attributes": {
                                "auth-type": "SMS"
                            }   
                        }, 
                    "paymentVOList": [ { "id": 12345 } ], 
                    "amount": 200000, 
                    "dueDate": 1425513600, 
                    "status": "NEW"
                },
                {
                    "id": 4, 
                    "paymentPlanVO": {
                            "id": 2, 
                            "period": "WEEKLY", 
                            "total": 1000000, 
                            "status": "PROCESSING", 
                            "whenLogged": 1420416000, 
                            "attributes": {
                                "auth-type": "SMS"
                            }   
                        }, 
                    "paymentVOList": [ { "id": 12345 } ], 
                    "amount": 200000, 
                    "dueDate": 1428192000, 
                    "status": "NEW"
                },
                {
                    "id": 5, 
                    "paymentPlanVO": {
                            "id": 2, 
                            "period": "WEEKLY", 
                            "total": 1000000, 
                            "status": "PROCESSING", 
                            "whenLogged": 1420416000, 
                            "attributes": {
                                "auth-type": "SMS"
                            }   
                        }, 
                    "paymentVOList": [ { "id": 12345 } ], 
                    "amount": 200000, 
                    "dueDate": 1430784000, 
                    "status": "NEW"
                }

            ]
        }
        
## getAllPaymentSchedule3 [/payment/account/plan/3/schedule]
### getAllPaymentSchedule3 [GET]

+ Body
    + name = "name" (optional, String, "myName")
    + groupId = "groupId" (optional, long, "1")

+ Response 200 (application/json)

        {
            "info": {
             }, 
            "errors": [
            ], 
            "data": [
                {
                    "id": 1, 
                    "paymentPlanVO": {
                            "id": 3, 
                            "period": "MONTHLY", 
                            "total": 500, 
                            "status": "NEW", 
                            "whenLogged": 1433116800, 
                            "attributes": {
                                "auth-type": "AUTOMATIC"
                            }
                        }, 
                    "paymentVOList": [ { "id": 12345 } ], 
                    "amount": 250, 
                    "dueDate": 1433116800, 
                    "status": "NEW"
                }, 
               {
                    "id": 2, 
                    "paymentPlanVO": {
                            "id": 3, 
                            "period": "MONTHLY", 
                            "total": 500, 
                            "status": "NEW", 
                            "whenLogged": 1433116800, 
                            "attributes": {
                                "auth-type": "AUTOMATIC"
                            }
                        }, 
                    "paymentVOList": [ { "id": 12345 } ], 
                    "amount": 250, 
                    "dueDate": 1435708800, 
                    "status": "NEW"
                }

            ]
        }        
        
## getPropertyByKeySystemCurrency [/properties/system.currency]
### getPropertyByKeySystemCurrency [GET]

+ Body
    + name = "name" (optional, String, "myName")
    + groupId = "groupId" (optional, long, "1")

+ Response 200 (application/json)

        {
            "info": {
             }, 
            "errors": [
            ], 
            "data": [
                {
                    "id" : 1,
                    "brand" : null,
                    "key" : "system.currency",
                    "value" : "USD"
                }
            ]
        }
        
## getPropertyByKeySystemCurrency [/properties/max.number.of.plan.cancellations]
### getPropertyByKeySystemCurrency [GET]

+ Body
    + name = "name" (optional, String, "myName")
    + groupId = "groupId" (optional, long, "4")

+ Response 200 (application/json)

        {
            "info": {
             }, 
            "errors": [
            ], 
            "data": [
                {
                    "id" : 1,
                    "brand" : null,
                    "key" : "max.number.of.plan.cancellations",
                    "value" : "4"
                }
            ]
        }
        
## getPropertyByKeyMaxAccountsAllowed [/properties/wallet.max.accounts.allowed]
### getPropertyByKeyMaxAccountsAllowed [GET]

+ Body
    + name = "name" (optional, String, "myName")
    + groupId = "groupId" (optional, long, "1")

+ Response 200 (application/json)

        {
            "info": {
             }, 
            "errors": [
            ], 
            "data": [
                {
                    "id" : 1,
                    "brand" : null,
                    "key" : "system.currency",
                    "value" : "2"
                }
            ]
        }

## getPropertyByKeyMaxAccountsAllowed [/properties/tenant.specific.date.format.spaced]
### getPropertyByKeyMaxAccountsAllowed [GET]

+ Body
    + name = "name" (optional, String, "myName")
    + groupId = "groupId" (optional, long, "1")

+ Response 200 (application/json)

        {
            "info": {
             }, 
            "errors": [
            ], 
            "data": [
                {
                    "id" : 1,
                    "brand" : null,
                    "key" : "system.currency",
                    "value" : "dd MMM yy"
                }
            ]
        }   
        
## getPaymentPlanRule [/payment/plan/rule]
### getPaymentPlanRule [GET]

+ Body
    + name = "name" (optional, String, "myName")
    + groupId = "groupId" (optional, long, "1")

+ Response 200 (application/json)

        {
            "info": {
             }, 
            "errors": [
            ], 
            "data": [
                {
                    "paymentType": "PAYNOW",
                    "allowedPaymentSources": [
                        {
                        "id": 12345, 
                        "customerVO": { "id": 12345 }, 
                        "name": "Lloyds card", 
                        "sequence": 1, 
                        "type": "VISA DEBIT", 
                        "active": true, 
                        "attributes": {
                            "nameOnCard": "Mr Alex Kidd", 
                            "expiry": "0116",
                            "alias" : "myAlias"
                        },
                        "whenLogged": 1423145227399,
                        "accountNumber": "4444"
                        }
                    ],
                    "notAllowedPaymentSources": [
                    ],  
                    "paymentTypeRules": {
                        "minimum.payments": 2, 
                        "maximum.payments": 10, 
                        "default.frequency": "WEEKLY",
                        "authorisation.method": "BOTH",
                        "minimun.interval.days": "5",
                        "maximun.interval.days": "10",
                        "minimun.accept.amount": "5000",
                        "maximun.accept.amount": "5000",
                        "max.changes.allowed" : 5,
                        "payment.changes" : 0
                        }
                },
                {
                    "paymentType": "FDP",
                    "allowedPaymentSources": [
                        {
                        "id": 12345, 
                        "customerVO": { "id": 12345 }, 
                        "name": "Lloyds card", 
                        "sequence": 1, 
                        "type": "VISA DEBIT", 
                        "active": true, 
                        "attributes": {
                            "nameOnCard": "Mr Alex Kidd", 
                            "expiry": "0116",
                            "alias" : "myAlias"
                        },
                        "whenLogged": 1423145227399,
                        "accountNumber": "4444"
                        }
                    ],
                    "notAllowedPaymentSources": [
                    ],  
                    "paymentTypeRules": {
                        "minimum.payments": 2, 
                        "maximum.payments": 10, 
                        "default.frequency": "WEEKLY",
                        "authorisation.method": "BOTH",
                        "minimun.interval.days": "5",
                        "maximun.interval.days": "10",
                        "minimun.accept.amount": "5000",
                        "maximun.accept.amount": "5000",
                        "max.changes.allowed" : 5,
                        "payment.changes" : 0
                        }
                },
                {
                    "paymentType": "PLAN",
                    "allowedPaymentSources": [
                        {
                        "id": 12345, 
                        "customerVO": { "id": 12345 }, 
                        "name": "Lloyds card", 
                        "sequence": 1, 
                        "type": "VISA DEBIT", 
                        "active": true, 
                        "attributes": {
                            "nameOnCard": "Mr Alex Kidd", 
                            "expiry": "0116",
                            "alias" : "myAlias"
                        },
                        "whenLogged": 1423145227399,
                        "accountNumber": "4444"
                        }
                    ],
                    "notAllowedPaymentSources": [
                    ],  
                    "paymentTypeRules": {
                        "minimum.payments": 2, 
                        "maximum.payments": 10, 
                        "default.frequency": "WEEKLY",
                        "authorisation.method": "BOTH",
                        "minimun.interval.days": "5",
                        "maximun.interval.days": "10",
                        "minimun.accept.amount": "5000",
                        "maximun.accept.amount": "5000",
                        "max.changes.allowed" : 5,
                        "payment.changes" : 0
                        }
                },
                {
                    "paymentType": "PAID",
                    "allowedPaymentSources": [
                        {
                        "id": 12345, 
                        "customerVO": { "id": 12345 }, 
                        "name": "Lloyds card", 
                        "sequence": 1, 
                        "type": "VISA DEBIT", 
                        "active": true, 
                        "attributes": {
                            "nameOnCard": "Mr Alex Kidd", 
                            "expiry": "0116",
                            "alias" : "myAlias"
                        },
                        "whenLogged": 1423145227399,
                        "accountNumber": "4444"
                        }
                    ],
                    "notAllowedPaymentSources": [
                    ],  
                    "paymentTypeRules": {
                        "minimum.payments": 2, 
                        "maximum.payments": 10, 
                        "default.frequency": "WEEKLY",
                        "authorisation.method": "BOTH",
                        "minimun.interval.days": "5",
                        "maximun.interval.days": "10",
                        "minimun.accept.amount": "5000",
                        "maximun.accept.amount": "5000",
                        "max.changes.allowed" : 5,
                        "payment.changes" : 0
                        }
                }
                ]
            }
            
# Group I&E PROCESS
**The resources**:
- **GET ie/item(List all I&E questions)**
- **PUT ie/process(Start a new I&E process)**
- **POST ie/process(Submit a collection of I&E answers)**

## I&E ITEM [/ie/item]
### I&E ITEM - RETRIEVE QUESTIONS[GET]
- **METHOD:** GET /ie/item
- **REQUEST OBJECT:** accountId
- **RESPONSE Object:** IeItemVO[]
- **DESCRIPTION:** This initial call will fetch all available questions regardless of user type. The response object will be an array of questions to collect

+ Response 200 (application/json)

          {
            "data": [
                {
                    "id": "SW1",
                    "ieGroupVO": "Salary or wages",
                    "tabId": "2",
                    "questionType": "PROFILING",
                    "priority": "Off",
                    "inputType": "Radio Select",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "SW2",
                    "ieGroupVO": "Salary or wages",
                    "tabId": "2",
                    "questionType": "INCOME",
                    "priority": "Off",
                    "name": "Take home salary or wages",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "SW3",
                    "ieGroupVO": "Salary or wages",
                    "tabId": "2",
                    "questionType": "INCOME",
                    "priority": "Off",
                    "name": "Partners take home salary or wages",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "B1",
                    "ieGroupVO": "Benefits",
                    "tabId": "4",
                    "questionType": "PROFILING",
                    "priority": "Off",
                    "name": "Do you receive any kind of government benefits",
                    "inputType": "Radio Select",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "B2",
                    "ieGroupVO": "Benefits",
                    "tabId": "4",
                    "questionType": "INCOME",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "B3",
                    "ieGroupVO": "Benefits",
                    "tabId": "4",
                    "questionType": "INCOME",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "B4",
                    "ieGroupVO": "Benefits",
                    "tabId": "4",
                    "questionType": "INCOME",
                    "priority": "Off",
                    "name": "Income Support",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "B5",
                    "ieGroupVO": "Benefits",
                    "tabId": "4",
                    "questionType": "INCOME",
                    "priority": "Off",
                    "name": "Working Tax Credits",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "B6",
                    "ieGroupVO": "Benefits",
                    "tabId": "4",
                    "questionType": "INCOME",
                    "priority": "Off",
                    "name": "Child Benefit",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "B7",
                    "ieGroupVO": "Benefits",
                    "tabId": "4",
                    "questionType": "INCOME",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "B8",
                    "ieGroupVO": "Benefits",
                    "tabId": "4",
                    "questionType": "INCOME",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "B9",
                    "ieGroupVO": "Benefits",
                    "tabId": "4",
                    "questionType": "INCOME",
                    "priority": "Off",
                    "name": "Housing Benefits",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "B10",
                    "ieGroupVO": "Benefits",
                    "tabId": "4",
                    "questionType": "INCOME",
                    "priority": "Off",
                    "name": "Coucil Tax Reduction",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "P1",
                    "ieGroupVO": "Pensions",
                    "tabId": "6",
                    "questionType": "PROFILING",
                    "priority": "Off",
                    "name": "Are you collecting a pension",
                    "inputType": "Radio Select",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "P2",
                    "ieGroupVO": "Pensions",
                    "tabId": "6",
                    "questionType": "INCOME",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "P3",
                    "ieGroupVO": "Pensions",
                    "tabId": "6",
                    "questionType": "INCOME",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "P4",
                    "ieGroupVO": "Pensions",
                    "tabId": "6",
                    "questionType": "INCOME",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "OI1",
                    "ieGroupVO": "Other Income",
                    "tabId": "6",
                    "questionType": "INCOME",
                    "priority": "Off",
                    "name": "Other",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "H1",
                    "ieGroupVO": "House or Flat",
                    "tabId": "9",
                    "questionType": "PROFILING",
                    "priority": "Off",
                    "name": "Do you own any property",
                    "inputType": "Radio Select",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "H2",
                    "ieGroupVO": "House or Flat",
                    "tabId": "9",
                    "questionType": "ASSET",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "H3",
                    "ieGroupVO": "House or Flat",
                    "tabId": "9",
                    "questionType": "ASSET",
                    "priority": "Off",
                    "name": "Mortgage outstanding",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "H4",
                    "ieGroupVO": "House or Flat",
                    "tabId": "9",
                    "questionType": "ASSET",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "H5",
                    "ieGroupVO": "House or Flat",
                    "tabId": "9",
                    "questionType": "EXPENDITURE",
                    "priority": "On",
                    "name": "How much is your Mortgage payment",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "H6",
                    "ieGroupVO": "House or Flat",
                    "tabId": "9",
                    "questionType": "EXPENDITURE",
                    "priority": "On",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "R1",
                    "ieGroupVO": "Rent",
                    "tabId": "11",
                    "questionType": "PROFILING",
                    "priority": "Off",
                    "name": "Do you pay rent on a property",
                    "inputType": "Radio Select",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "R2",
                    "ieGroupVO": "Rent",
                    "tabId": "11",
                    "questionType": "EXPENDITURE",
                    "priority": "On",
                    "name": "Rent",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "R3",
                    "ieGroupVO": "Rent",
                    "tabId": "11",
                    "questionType": "EXPENDITURE",
                    "priority": "On",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "R4",
                    "ieGroupVO": "Rent",
                    "tabId": "11",
                    "questionType": "EXPENDITURE",
                    "priority": "On",
                    "name": "Other secured loans",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "TR1",
                    "ieGroupVO": "Travel",
                    "tabId": "13",
                    "questionType": "PROFILING",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "TR2",
                    "ieGroupVO": "Travel",
                    "tabId": "13",
                    "questionType": "ASSET",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "TR3",
                    "ieGroupVO": "Travel",
                    "tabId": "13",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "name": "Car insurance",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "TR4",
                    "ieGroupVO": "Travel",
                    "tabId": "13",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "name": "Vehicle Tax",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "TR5",
                    "ieGroupVO": "Travel",
                    "tabId": "13",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "TR6",
                    "ieGroupVO": "Travel",
                    "tabId": "13",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "name": "MOT and car maintenance",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": ""
                },
                {
                    "id": "TR7",
                    "ieGroupVO": "Travel",
                    "tabId": "13",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "name": "Breakdown or recovery",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "TR8",
                    "ieGroupVO": "Travel",
                    "tabId": "13",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "name": "Parking charges or tolls",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "TR9",
                    "ieGroupVO": "Travel",
                    "tabId": "13",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "name": "Other car costs",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "OT1",
                    "ieGroupVO": "Other Travel Costs",
                    "tabId": "13",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "OT2",
                    "ieGroupVO": "Other Travel Costs",
                    "tabId": "13",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "OA1",
                    "tabId": "16",
                    "questionType": "PROFILING",
                    "priority": "Off",
                    "inputType": "Radio Select",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "OA2",
                    "ieGroupVO": "Other Assets",
                    "tabId": "16",
                    "questionType": "ASSET",
                    "priority": "Off",
                    "name": "Savings",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "OA3",
                    "ieGroupVO": "Other Assets",
                    "tabId": "16",
                    "questionType": "ASSET",
                    "priority": "Off",
                    "name": "Other assets",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "H1",
                    "ieGroupVO": "Household",
                    "tabId": "17",
                    "questionType": "PROFILING",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "H2",
                    "ieGroupVO": "Household",
                    "tabId": "17",
                    "questionType": "PROFILING",
                    "priority": "Off",
                    "inputType": "Radio Select",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "C2",
                    "ieGroupVO": "Children",
                    "tabId": "18",
                    "questionType": "PROFILING",
                    "priority": "Off",
                    "name": "Dependant children under 14",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "C3",
                    "ieGroupVO": "Children",
                    "tabId": "18",
                    "questionType": "PROFILING",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "C4",
                    "ieGroupVO": "Children",
                    "tabId": "18",
                    "questionType": "PROFILING",
                    "priority": "Off",
                    "name": "Dependant children in household",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "C5",
                    "ieGroupVO": "Children",
                    "tabId": "18",
                    "questionType": "EXPENDITURE",
                    "priority": "On",
                    "name": "Maintenance or child support",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "C6",
                    "ieGroupVO": "Children",
                    "tabId": "18",
                    "questionType": "EXPENDITURE",
                    "priority": "On",
                    "name": "Childcare costs",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "C7",
                    "ieGroupVO": "Children",
                    "tabId": "18",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "name": "School meals and meals at work",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "C8",
                    "ieGroupVO": "Children",
                    "tabId": "18",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "name": "Pocket money and school trips",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "C9",
                    "ieGroupVO": "Children",
                    "tabId": "18",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "name": "Nappies and baby items",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "HB1",
                    "ieGroupVO": "Household Bills",
                    "tabId": "19",
                    "questionType": "EXPENDITURE",
                    "priority": "On",
                    "name": "Building and contents insurance",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "HB2",
                    "ieGroupVO": "Household Bills",
                    "tabId": "19",
                    "questionType": "EXPENDITURE",
                    "priority": "On",
                    "name": "Pension and life insurance",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "HB3",
                    "ieGroupVO": "Household Bills",
                    "tabId": "19",
                    "questionType": "EXPENDITURE",
                    "priority": "On",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "HB4",
                    "ieGroupVO": "Household Bills",
                    "tabId": "19",
                    "questionType": "EXPENDITURE",
                    "priority": "On",
                    "name": "Gas",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "HB5",
                    "ieGroupVO": "Household Bills",
                    "tabId": "19",
                    "questionType": "EXPENDITURE",
                    "priority": "On",
                    "name": "Electricity",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "HB6",
                    "ieGroupVO": "Household Bills",
                    "tabId": "19",
                    "questionType": "EXPENDITURE",
                    "priority": "On",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "HB8",
                    "ieGroupVO": "Household Bills",
                    "tabId": "19",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "name": "Home phone",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "HB9",
                    "ieGroupVO": "Household Bills",
                    "tabId": "19",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "name": "Mobile phone",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "HB11",
                    "ieGroupVO": "Household Bills",
                    "tabId": "19",
                    "questionType": "EXPENDITURE",
                    "priority": "On",
                    "name": "TV licence",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "HB12",
                    "ieGroupVO": "Household Bills",
                    "tabId": "19",
                    "questionType": "EXPENDITURE",
                    "priority": "On",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "HB13",
                    "ieGroupVO": "Household Bills",
                    "tabId": "19",
                    "questionType": "EXPENDITURE",
                    "priority": "On",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "HB14",
                    "ieGroupVO": "Household Bills",
                    ,
                    "tabId": "19",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "HB15",
                    "ieGroupVO": "Household Bills",
                    "tabId": "19",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "LC1",
                    "ieGroupVO": "Living Costs",
                    "tabId": "20",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "name": "Food and milk",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "LC2",
                    "ieGroupVO": "Living Costs",
                    "tabId": "20",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "name": "Cleaning and toiletries",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "LC3",
                    "ieGroupVO": "Living Costs",
                    "tabId": "20",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "name": "Clothing and footwear",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "LC4",
                    "ieGroupVO": "Living Costs",
                    "tabId": "20",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "name": "Pet food",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "LC5",
                    "ieGroupVO": "Living Costs",
                    "tabId": "20",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "name": "Other housekeeping",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "LC6",
                    "ieGroupVO": "Living Costs",
                    "tabId": "20",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "name": "Laundry and dry cleaning",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "LC7",
                    "ieGroupVO": "Living Costs",
                    "tabId": "20",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "LC8",
                    "ieGroupVO": "Living Costs",
                    "tabId": "20",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "LC9",
                    "ieGroupVO": "Living Costs",
                    "tabId": "20",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "LC10",
                    "ieGroupVO": "Living Costs",
                    "tabId": "20",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "LC11",
                    "ieGroupVO": "Living Costs",
                    "tabId": "20",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "name": "Vet bills and pet insurance",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "LC12",
                    "ieGroupVO": "Living Costs",
                    "tabId": "20",
                    "questionType": "EXPENDITURE",
                    "priority": "On",
                    "name": "Adult care costs",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "LE1",
                    "ieGroupVO": "Leisure",
                    "tabId": "21",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "name": "Newspapers and magazines",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "LE2",
                    "ieGroupVO": "Leisure",
                    "tabId": "21",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "LE3",
                    "ieGroupVO": "Leisure",
                    "tabId": "21",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "name": "Alcohol",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "LE4",
                    "ieGroupVO": "Leisure",
                    "tabId": "21",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "name": "Lottery and pools etc",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "LE5",
                    "ieGroupVO": "Leisure",
                    "tabId": "21",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "OE1",
                    "ieGroupVO": "Other Expenditure",
                    "tabId": "21",
                    "questionType": "EXPENDITURE",
                    "priority": "Off",
                    "name": "Other ",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "D1",
                    "ieGroupVO": "Debts",
                    "tabId": "24",
                    "questionType": "PROFILING",
                    "priority": "Off",
                    "name": "Do you have any outstadning debts or arears",
                    "inputType": "Radio Select",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "D2",
                    "ieGroupVO": "Debts",
                    "tabId": "24",
                    "questionType": "DEBTS",
                    "priority": "On",
                    "name": "Rent",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Off"
                },
                {
                    "id": "D3",
                    "ieGroupVO": "Debts",
                    "tabId": "24",
                    "questionType": "DEBTS",
                    "priority": "On",
                    "name": "Mortgage",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Debt repayment amount"
                },
                {
                    "id": "D4",
                    "ieGroupVO": "Debts",
                    "tabId": "24",
                    "questionType": "DEBTS",
                    "priority": "On",
                    "name": "Other secured loans",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Debt repayment amount"
                },
                {
                    "id": "D5",
                    "ieGroupVO": "Debts",
                    "tabId": "24",
                    "questionType": "DEBTS",
                    "priority": "On",
                    "name": "Magistrates or sheriff court fine",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Debt repayment amount"
                },
                {
                    "id": "D6",
                    "ieGroupVO": "Debts",
                    "tabId": "24",
                    "questionType": "DEBTS",
                    "priority": "On",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Debt repayment amount"
                },
                {
                    "id": "D7",
                    "ieGroupVO": "Debts",
                    "tabId": "24",
                    "questionType": "DEBTS",
                    "priority": "On",
                    "name": "Maintenance or child support",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Debt repayment amount"
                },
                {
                    "id": "D8",
                    "ieGroupVO": "Debts",
                    "tabId": "24",
                    "questionType": "DEBTS",
                    "priority": "On",
                    "name": "Gas",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Debt repayment amount"
                },
                {
                    "id": "D9",
                    "ieGroupVO": "Debts",
                    "tabId": "24",
                    "questionType": "DEBTS",
                    "priority": "On",
                    "name": "Electricity",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Debt repayment amount"
                },
                {
                    "id": "D10",
                    "ieGroupVO": "Debts",
                    "tabId": "24",
                    "questionType": "DEBTS",
                    "priority": "On",
                    "name": "Hire purchase or conditional sale",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Debt repayment amount"
                },
                {
                    "id": "D13",
                    "ieGroupVO": "Non Priority Debts",
                    "tabId": "24",
                    "questionType": "DEBTS",
                    "priority": "on",
                    "name": "Other",
                    "inputType": "Text Box",
                    "periodField": "Monthly",
                    "value2Field": "Debt repayment amount"
                }
            ]
          }

## I&E PROCESS [/ie/process]
### I&E PROCESS - RETRIEVE GROUPS[POST]
- **METHOD:** POST /ie/process
- **REQUEST OBJECT:** accountId
- **RESPONSE Object:** ieGroupVO[]
- **DESCRIPTION:** This initial call will either start a new I&E process or continue an existing one (for the submitted accountId). The response object will be an array of tabId to collect

+ Response 200 (application/json)

        {
          "data": [
              {
                  "order": "1",
                  "id": "2",
                  "name": "Salary or wages",
                  "whenlogged": "1416498870788"
              },
              {
                  "order": "2",
                  "id": "4",
                  "name": "Benefits",
                  "whenlogged": "1416498870788"
              },
              {
                  "order": "3",
                  "id": "6",
                  "name": "Pensions",
                  "whenlogged": "1416498870788"
              },
              {
                  "order": "4",
                  "id": "9",
                  "name": "House or Flat",
                  "whenlogged": "1416498870788"
              },
              {
                  "order": "5",
                  "id": "11",
                  "name": "Rent",
                  "whenlogged": "1416498870788"
              },
              {
                  "order": "6",
                  "id": "13",
                  "name": "Travel",
                  "whenlogged": "1416498870788"
              },
              {
                  "order": "7",
                  "id": "16",
                  "name": {
                      "$t": "Other Assets/Savings"
                  },
                  "whenlogged": "1416498870788"
              },
              {
                  "order": "8",
                  "id": "17",
                  "name": "Household",
                  "whenlogged": "1416498870788"
              },
              {
                  "order": "9",
                  "id": "18",
                  "name": "Children",
                  "whenlogged": "1416498870788"
              },
              {
                  "order": "10",
                  "id": "19",
                  "name": "Household Bills",
                  "whenlogged": "1416498870788"
              },
              {
                  "order": "11",
                  "id": "20",
                  "name": "Living Costs",
                  "whenlogged": "1416498870788"
              },
              {
                  "order": "12",
                  "id": "21",
                  "name": "Leisure",
                  "whenlogged": "1416498870788"
              },
              {
                  "order": "13",
                  "id": "24",
                  "name": "Debts",
                  "whenlogged": "1416498870788"
              }
          ]
        }

### I&E PROCESS - SAVE ANSWERS[PUT]
- **METHOD:** PUT /ie/process
- **REQUEST OBJECT:** IEAnswerVO
- **RESPONSE Object:** ieGroupVO[]
- **DESCRIPTION:** This method will evaluate the submitted answers and  return; a group of questions to ask.

- **Request object sample:
        **{
        "id": 12345,
         "status": "COMPLETE",
         "totalIncome": 20,
         "totalExpenditure": 10,
         "ieItemAnswerVOSet": [
             {
                 "id": 12345,
                 "value": "10.00",
                 "value2": null,
                   "notes": "Some customer notes",
                   "period": "MONTHLY",
                   "whenLogged": 1421932232400,
                   "ieItemVO": {
                       "id": 12345
                 }
             }
         ],
         "customerVO": {
             "id": 12345
         },
         "customerAccountVO": {
             "id": 12345
         },
         "whenLogged": 1421932232408,
         "whenCompleted": 1421932232408,
         }**

+ Response 200 (application/json)

        {
          "info": {
            "text": "Successfully uploaded",
            "key": "some.info.text"
            }
        }
